### ISSUE TITLE
Map marker v3.4.0_572_beta

### ISSUE THREAD

**Issue by fraiyah** [androidseb/mapmarker#1]
Hi dev 

 I would like to report an issue on marker searchbar the cursor seems to be buggy it automatically change direction when trying to input letters or numbers to search, i hope you can fix this quickly thank you

**Comment by androidseb** [comment]
Hey, thanks for reporting this!

This is now fixed with version 3.4.0_574_beta, which should be available for download within a few hours. If you're still experiencing the issue after updating, please re-open this issue and let me know, thanks!
