### ISSUE TITLE
Ability to rotate the map on web

### ISSUE THREAD

**Issue by androidseb** [androidseb/mapmarker#16]
It is currently not possible to rotate the map on web using a PC. This item is about making this possible.

**Comment by sballe73** [comment]
looks like when we right clic it turns into zoom and rotate mode. But how do you quit this mode ?

**Comment by androidseb** [comment]
I'm not aware of this, are you talking about the PC web app?

What PC + OS + browser are you using to achieve this? Right click for me just brings the browser menu, not related to the app...

**Comment by sballe73** [comment]
it does bring the context menu, but it also triggers this unescapable zoom and rotate mode :)
Using Firefox on Linux
once in the mode I have to refresh (and most of the time resync to the cloud) but the angle of rotation is kept

**Comment by androidseb** [comment]
I was not aware that this was happening. I just tried it on Firefox and I was able to reproduce this.

I believe this is a bug, here is my interpretation of what is happening... When you right-click on the map with Firefox:
* The "touch down" event is registered on the map at that precise screen location you right-clicked
* The context menu appears
* You let go of the right click button, but the "touch up" even is never transmitted back to the map
* If you use the left click to drag on the map, it's as if you had a second "touch down" event, the first one being where you originally right-clicked
* It remains stuck like this until you reload the page

So this behavior is a bug with the Firefox browser...

This improvement will make it possible to rotate the map intentionally.

**Comment by androidseb** [comment]
Flutter Map V6 will support this:
* It was requested here: https://github.com/fleaflet/flutter_map/discussions/1511
* It was implemented here: https://github.com/fleaflet/flutter_map/pull/1592

You can test this using their demo page (based on the master branch), holding "Ctrl" on your keyboard allows you to rotate the map when dragging:
https://demo.fleaflet.dev/

Once the V6 is released, I'll upgrade the library version used by Map Marker and this improvement will be included automatically, thank you flutter_map team!!!.

**Comment by androidseb** [comment]
Done in 3.7.0-beta-637.
You can rotate the map by holding the Ctrl key and dragging the mouse.

**Comment by sballe73** [comment]
Cool, will try

**Comment by sballe73** [comment]
it works
