### ISSUE TITLE
Gps calibration inside the map marker

### ISSUE THREAD

**Issue by fraiyah** [androidseb/mapmarker#26]
Good day i would like to make some additional features like gps calibration tools inside the app the will always make sure that the current location is on the right path and will show the status of the accuracy of the current location

thank you dev hoping this project will become successfull and will help a lot of industry like electric company like mine and telecommunition company and small time delivery company

**Comment by androidseb** [comment]
Hey, thanks for proposing this idea!

Could you share a little bit more details on what you would be expecting to do with this? What would you expect from this "GPS calibration tool" exactly?

"Calibration" implies there are some actions to adjust the GPS behavior, is that really what you mean? Or do you mean some tool displaying "read only" information currently available from the device's GPS, such as accuracy etc.?

**Comment by fraiyah** [comment]
Hi dev

what i mean to say is the ability of the map marker to detect if my current location accuracy is low, mid or high as a read only view and then later on it can have manual calibration inside the app to make sure that the location is accurate by the way this concern is only on android devices. ios devices is not affected because ios has a better location accuracy.


kind regards,

**Comment by androidseb** [comment]
I'm not sure what you mean by "having a manual calibration inside the app"...

Currently, the radius circle around your location shows the accuracy of the GPS location, but as far as I know, there isn't much the apps can do to improve the accuracy, since Map Marker already requests maximum accuracy to the system when requesting device GPS location.

Could you clarify what you would expect the app to for this improvement please? Thanks!

**Comment by fraiyah** [comment]
Hi Seb 

thanks for replying on this issue may be you can close this issue since you mention that the app already request the most accurate gps location to the system, i think the accuracy now will depend on how the system ability to precisely get the most qccurwte location ,maybe lower model or old phones like my android seems to have a trouble gettinf accurate positioning and it takes time to update the current location, in my ios devices though seems to be more precise and updates the current location much faster when using map marker app, compared to the android devices
