### ISSUE TITLE
Penambahan fitur di MAp Marker

### ISSUE THREAD

**Issue by Fadli1994** [androidseb/mapmarker#32]
1. Sebaiknya di sediakan kilometer awal sampai akhir perjalanan
2. Sebaiknya disediakan fitur seperti google maps yang dapat mengunjungi beberapa tempat sekaligus jalan dengan alternatif jalur tercepat
Terima kasih

**Comment by androidseb** [comment]
Hello, thanks for suggesting ideas!

Unfortunately, I don't speak Indonesian, so I'll paste your Google-translated message here below. Please use English to help me with communication, thanks!

* Title: "Added features to Map Marker"
* Messages:
    * 1: It is best to provide kilometers from the start to the end of the trip
    * 2: It would be better to provide features such as Google Maps which can visit several places at once using the fastest alternative route
    * "Thank you"

Just to be clear, Map Marker is not a navigation app, and will not try to be, see why [here](https://www.mapmarker.app/help/index.html?device=android#devices_android_Why_is_Map_Marker_not_a_navigation_app).

About what you asked...

## About 1: It is best to provide kilometers from the start to the end of the trip

It is already possible to draw a path on the map and measure its distance, is that what you're asking for, or is it something else?

## About 2: It would be better to provide features such as Google Maps which can visit several places at once using the fastest alternative route

If I understand this correctly, you'd like to see a feature where we can select multiple points, and compute the most optimal path to visit all those points? Did I get this right?

**Comment by androidseb** [comment]
There hasn't been any recent activity on this issue, I will now close it to keep the backlog clear of stale issues. Feel free to re-open as needed, thank you.
