### ISSUE TITLE
ADDING OF ROUTE MAP FOR EXISTING LOCATION 

### ISSUE THREAD

**Issue by vikashSGI** [androidseb/mapmarker#45]
SIR, im using this map marker for marketing for past 2 years. Our process is that, We go to new customer location and  add their location and fill the details of them and their usage ( i.e, what segment? , what product they are using? , what price, what consumption, what free sample product of our have u given and result) . We ask our marketing person to fill this . At first time when he goes , he fill all this stuffs and come. To ask the result , another person from sales team has to go and update these information. As the sales person goes he leaves some location in the middle. So it will be better if there is a creation of route map(connecting the locations by the order). so that i can create the list of locations he have to visit and share it to him.

**Comment by androidseb** [comment]
Hello, thanks for the suggestion. How is this different from creating a line with multiple points, and editing the line to add a new point each time? I guess with the line there is no "direction"? By "route", do you mean an ordered path with ranked and timestamped points? Are you looking to edit the different points individually, or should they all share the same title / description?

**Comment by androidseb** [comment]
There hasn't been any recent activity on this issue, I will now close it to keep the backlog clear of stale issues. Feel free to re-open as needed, thank you.
