### ISSUE TITLE
"ADD CUSTOM FIELD" IMPROVEMENTS - (others option required in multiple choice & selecting more options on multiple choice)

### ISSUE THREAD

**Issue by vikashSGI** [androidseb/mapmarker#46]
SIR, im using this map marker for marketing for past 2 years. Our process is that, We go to new customer location and add their location and select the correct folder and fill the details of them and their usage ( **i.e, what segment? , what product they are using? , what price, what consumption, what free sample product of our have u given and result**) . We ask our marketing person to fill this . Most of this questions are multiple choice questions. So if we give 5 options , he have to choose one or more than one. But the option in the app is limited to choosing only one option. Also kindly add OTHERS option in multiple choice (i.e If they have to choose a option apart from this 5 options, an Others column can be choosed and answer can be typed) . You can check google forms for a better idea. (I have attached a link - https://forms.gle/q8DsFqxNS2HyiayJ7 ) . Kindly check and add this . Thankyou

**Comment by androidseb** [comment]
Hey, thanks for the suggestion. I had the multiple selection listed out [here in the ideas to triage](https://github.com/androidseb/mapmarker/issues/3), but I didn't have the "others" option, that's an interesting one to add too.

I think your suggestion can be summarized to the following:

## Title

> Multiple choice custom field improvements: multi-option selection and "other" free text choice

## Description

> Currently the "multi choice" custom field presents the user with several choices, but they can only select a single option. Also, if the option is not in the list, they cannot easily select it. This change aims to allow for two additional improvements:
>
> 1. Allow selecting more than one option
> 2. Allow for entering a custom user-entered option

## Plan of implementation

> * Rename the current "multi choice" custom field allowing for a single choice to "single option"
> * Introduce a new custom field type "multi option" allowing to select several options
> * Add a boolean attribute (ON/OFF) denoting whether the "other" free text option is allowed as a choice

Could you please confirm I got this right?

**Comment by androidseb** [comment]
There hasn't been any recent activity on this issue, I will now close it to keep the backlog clear of stale issues. Feel free to re-open as needed, thank you.
