### ISSUE TITLE
Map Marker Improve Idea

### ISSUE THREAD

**Issue by Bombaz92** [androidseb/mapmarker#47]
Good morning,
I would like to know if it is possible to apply a method to export the photos taken in the field, to a folder that can be viewed separately, rather than having everything in KMZ format. This folder will be useful for sharing photos and georeferenced data across multiple devices and platforms.
Furthermore, it is possible to insert and display a path that can be followed during field activities??

A thousand thanks

**Comment by androidseb** [comment]
Hello, thank you for the suggestions.

For recording a track, I believe this is what you're looking for? https://github.com/androidseb/mapmarker/issues/4

For the pictures, right now what you can do is:

* Export your map as a KMZ file
* Rename the file to a .zip file
* Extract the zip archive
* Look at the "media" folder -> all your pictures are there

Is this what you're looking for, with the simplified steps of only selecting a target folder, or are you looking for more?

**Comment by androidseb** [comment]
There hasn't been any recent activity on this issue, I will now close it to keep the backlog clear of stale issues. Feel free to re-open as needed, thank you.
