### ISSUE TITLE
Polygon Pin - Button positions.

### ISSUE THREAD

**Issue by EDGE-ELITE** [androidseb/mapmarker#49]
Hi there,

I'd sent an email, but as it was recommended to leave a Github request, I thought I'd drop a message here too.

When creating a pin location using the polygon/shape tool, it's easy to accidentally press the 'Previous point' or 'Remove point' buttons when trying to add another point.
I just wondered if the idea of swapping the buttons over, or removing the 'Add New Point' button from that middle menu, and adding a larger circular button in the bottom left corner, may make the tool easier to use. I mocked up a quick example below:

![MapMarkerExamples](https://github.com/androidseb/mapmarker/assets/25804147/0479e7a0-711e-40fb-b8eb-c7af8a08f657)

Thank you for your efforts in developing this handy app. 👍

**Comment by androidseb** [comment]
Thanks for the suggestion, I had not thought about that. It is true swapping those buttons makes it less error-prone.

I'll add this to the backlog as an improvement item to be done soon, because it's trivial to implement and will make things easier for users.

**Comment by androidseb** [comment]
I've implemented this in the new beta version (3.8.0-beta-696), please let me know if you have feedback, thanks:

![Image](https://github.com/androidseb/mapmarker/assets/5169269/ce3309ea-6b66-4270-b789-cd4499426feb)

**Comment by EDGE-ELITE** [comment]
> I've implemented this in the new beta version (3.8.0-beta-696), please let me know if you have feedback, thanks

Hi there, unfortunately I cannot find the new beta version of the app. If it's not yet published, I'll be happy to try it when it is.

But looking at the image, it's much better than the already existing UI. I find when drawing the shapes, I'm using my right thumb to pan the point/crosshair around the screen, and I'm using my left thumb to add new points. That's why my initial thought was to have the plus at the left hand side. But the larger central button should make pressing other buttons in error less likely. 😊👍

**Comment by androidseb** [comment]
Hello, if you're OK taking a certain level of risk on stability, you can try out the beta by following instructions here:

https://www.mapmarker.app/help/index.html?device=android#devices_android_I_want_to_try_early_features_how_can_I_use_the_beta

Otherwise this will be released in the app update eventually, probably in less than 2 months from now.

**Comment by androidseb** [comment]
Released with version 3.8.0.
