### ISSUE TITLE
Duplicate marker

### ISSUE THREAD

**Issue by buddhafragt** [androidseb/mapmarker#50]
Ability to duplicate marker. (Copy/paste)?

**Comment by androidseb** [comment]
Thank you for the suggestion. Did you know you can already do this from the organizer view? When selecting/checking a POI in the list of the organizer, you have an option to make a copy. Is that what you were looking for, or were you looking for an easier way to do this?

**Comment by buddhafragt** [comment]
> Thank you for the suggestion. Did you know you can already do this from the organizer view? When selecting/checking a POI in the list of the organizer, you have an option to make a copy. Is that what you were looking for, or were you looking for an easier way to do this?

Thank you, this is what I am looking for!

**Comment by androidseb** [comment]
Thanks for confirming, I'll close this issue then, feel free to re-open it if you have more questions / requests on behavior changes.

**Comment by androidseb** [comment]
Thanks for confirming, I'll close this issue then, feel free to re-open it if you have more questions / requests on behavior changes.
