### ISSUE TITLE
Clear polygon shading 

### ISSUE THREAD

**Issue by MbungeNathan** [androidseb/mapmarker#51]
Option (or default) to clear (make invisible) the polygon shading when its folder is unchecked (in the same way the other POIs are made invisible).

**Comment by androidseb** [comment]
Hello, thanks for the suggestion, I'm not sure what you're asking for here, it seems you're describing a behavior that is already implemented in the app?

If you create a polygon, put it in a folder, and then un-select that folder, then the polygon will be hidden from the map (made invisible).

Is that not what is happening for you? Or are you talking about something else?

**Comment by androidseb** [comment]
There hasn't been any recent activity on this issue, I will now close it to keep the backlog clear of stale issues. Feel free to re-open as needed, thank you.
