### ISSUE TITLE
user defined fields

### ISSUE THREAD

**Issue by buddhafragt** [androidseb/mapmarker#58]
if I change a markers specific folder, user defined fields for this marker dont change to the folders fields.

**Comment by androidseb** [comment]
Hello, you have the option to do this from the top "..." menu button with the option "apply parent folder fields".

Is this what you were looking for?

**Comment by androidseb** [comment]
There hasn't been any recent activity on this issue, I will now close it to keep the backlog clear of stale issues. Feel free to re-open as needed, thank you.
