### ISSUE TITLE
sync error

### ISSUE THREAD

**Issue by buddhafragt** [androidseb/mapmarker#59]
if i open a cloud file from mapmarker android and open in mapmarker web it works, but if i try to safe it later back with sync, I get a sync-error.
![Bildschirmfoto 2024-04-10 um 19 05 35](https://github.com/androidseb/mapmarker/assets/680639/139802d2-7e6f-4e42-b944-f526ab6ce2f6)

**Comment by androidseb** [comment]
Hello, thank you for reporting this issue.

Are you getting this error message from your web browser? If so, what web browser are you using?

**Comment by androidseb** [comment]
There hasn't been any recent activity on this issue, I will now close it to keep the backlog clear of stale issues. Feel free to re-open as needed, thank you.
