### ISSUE TITLE
Leaving a trace on the map

### ISSUE THREAD

**Issue by tevfikmolguncelik** [androidseb/mapmarker#62]
It's nice to be able to see my current location on the map. If it is not a difficult thing, it can be added as a feature. When I activate this option, I want it to leave a trace behind me when I move.

**Comment by androidseb** [comment]
Hello, are you referring to the GPS track recording feature that was released about a month ago in version 3.7.0?

https://www.mapmarker.app/help/index.html?device=ios#devices_ios_Creating_a_Track

**Comment by androidseb** [comment]
There hasn't been any recent activity on this issue, I will now close it to keep the backlog clear of stale issues. Feel free to re-open as needed, thank you.
