### ISSUE TITLE
Hex grid

### ISSUE THREAD

**Issue by 4ermine** [androidseb/mapmarker#71]
Hello, developer.
Can you implement the hex grid mode in near future? I just like play wargames in google maps.

Truly yours,
4ermine.

**Comment by androidseb** [comment]
Hello, thanks for the suggestion. What is this hex grid mode you're talking about, is it a coordinates system? Do you have references to any documentation specifying how this works?

**Comment by androidseb** [comment]
There hasn't been any recent activity on this issue, I will now close it to keep the backlog clear of stale issues. Feel free to re-open as needed, thank you.
