### ISSUE TITLE
Support for Google Maps in the web version.

### ISSUE THREAD

**Issue by qazitasawur** [androidseb/mapmarker#75]
Please add google maps support in the web browser client.

**Comment by androidseb** [comment]
Hello, thank you for suggesting this idea.

Unfortunately, offering Google Maps on a web app is costly - in the case of Map Marker, it would cost several thousands of dollars per month to offer this, so this is not something I will pursue for the time being.

The only viable way I could do this is by letting users who have registered their own Google Developer account with their credit card configure their own API key in Map Marker, but I'm thinking that would be a very small portion of users, and I haven't seen demand for this yet.

Would you be among those users?

**Comment by androidseb** [comment]
There hasn't been any recent activity on this issue, I will now close it to keep the backlog clear of stale issues. Feel free to re-open as needed, thank you.
