### ISSUE TITLE
Search Sources broken

### ISSUE THREAD

**Issue by cdaller** [androidseb/mapmarker#77]
Hi!

I just started using MapMarker and find it really cool! So I went for premium right away :-)

The only thing that is not really great is the search.

So I tried to add a Search Source as described in your documentation:
* Bing Search API: it seems that MS stopped to provide API keys for Bing, as Bing Maps will be faded out and is replaced by Azure Maps
* Here: I created an account, projekct, app and API key as described, but the api key does not work: the message "Warning: the configurationtest  for the search source failed...." - probably the API changed? If you would provide more information about the api you are using, I could test myself (using curl or similar) - I am a software developer, so a hint (URL/path) would probably be enough :-)

Thanks for your help!

Cheers,
Christof

**Comment by androidseb** [comment]
Hello, thank you for reporting this.

You're correct, the Bing search API is no longer possible to set up, and the Here places search setup steps changed a little bit.

I've updated the help center page to remove "Bing" and updated instructions for "Here".

You can find the updated help center section here:
https://www.mapmarker.app/help/index.html?device=android#devices_android_Configuring_third_party_search_sources

Could you please take a look at the updated instructions and let me know if those work for you?

**Comment by cdaller** [comment]
Thanks for quick Adaption of the documentation. Unfortunately, it did not help. I am (and was before) able to create an api key, but the key does not work then. 

<img width="691" alt="image" src="https://github.com/user-attachments/assets/179f29e7-0a26-47c9-b4a1-678f122d744c">

This is how my here config looks like. On the bottom you see my (starred) api key I used.

<img width="768" alt="image" src="https://github.com/user-attachments/assets/9a7e0b05-d857-4130-ba40-4b8e86c9e7c0">

**Comment by cdaller** [comment]
Hmmm - it seems that my api keys are simply not allowed to retrieve anything. I tried with the exaples in the documentation and this does not work eiter:

```bash
curl "https://geocode.search.hereapi.com/v1/geocode?q=5+Rue+Daunou%2C+75000+Paris%2C+France&apiKey=xxx"
```

returns 

```json
{
  "title" : "These credentials do not authorize access for this operation.",
  "status" : 403,
  "code" : "403403",
  "cause" : "App 0A6KTt9ouyMFVb1rKhi0 credentials do not authorize access to perform read action on hrn:here:service::olp-here:search-geocode-7 via SERVICE-cc6db5a5-2135-4003-a2fa-5985a52dbcb0 or to perform invoke action on hrn:here:service::olp-here:search-geocode-7 via SERVICE-cc6db5a5-2135-4003-a2fa-5985a52dbcb0 or to perform getGeocode action via SERVICE-33d73656-c754-47e8-9b1d-31016f25cefc in scope of project hrn:here:authorization::org700990714:project/mapmarker because Resource relation is missing, Action is not permitted.",
  "action" : "Link the resource to the project, Retry with the allowed actions for access.",
  "error" : "Forbidden",
  "details" : [ {
    "decision" : "deny",
    "action" : "read",
    "resource" : "hrn:here:service::olp-here:search-geocode-7",
    "service" : "SERVICE-cc6db5a5-2135-4003-a2fa-5985a52dbcb0",
    "message" : "Resource relation is missing."
  }, {
    "decision" : "deny",
    "action" : "invoke",
    "resource" : "hrn:here:service::olp-here:search-geocode-7",
    "service" : "SERVICE-cc6db5a5-2135-4003-a2fa-5985a52dbcb0",
    "message" : "Resource relation is missing."
  }, {
    "decision" : "deny",
    "action" : "getGeocode",
    "service" : "SERVICE-33d73656-c754-47e8-9b1d-31016f25cefc",
    "message" : "Action is not permitted."
  } ],
  "error_description" : "These credentials do not authorize access"
}
```

Searching for this error does not give any helpful resuts. Very strange, but the problem does not seem to be on MapMarker app side, but on the here API side.

Any hints?

**Comment by androidseb** [comment]
Hello, thanks for testing this out.

I went through the full list of steps again with a brand new account to test it out.

I noticed a minor step was missing, so I replaced this single step:

> On the next page, the "API key" will be displayed to you, so you can copy it

With these two:

> On the next page, if no API key is already present, click "Create API key"
> On the API key, click either the "Copy" or "View" buttons so you can copy the API key to the clipboard

The newly created API key on my new account was working immediately with [the curl command you provided earlier](https://github.com/androidseb/mapmarker/issues/77#issuecomment-2282662469), so I'm not sure why you would face that response.

The only difference I can think of is that you specified "Map Marker" under the "Default project section", whereas in my newly created account, it just reads "Default project:  Not specified". Also, when creating my account, I specified the region of "France", I don't know if that has an impact.

Did you do this (adding the default project) yourself as an extra step, or did following my updated instructions lead you to creating that project? Could it be a remnant of the old instructions / old account maybe?

Could you try editing your app under https://platform.here.com/admin/apps to see if you can set the "default project" field to "not specified" and see if this resolves the issue for you?

Thank you in advance.

**Comment by cdaller** [comment]
Thanks for your super fast response. 

I recreated the Here App and a new API key was automatically created then. This key worked with my curl command above and was accepted by MapMarker app!

Thanks for your help!
