### ISSUE TITLE
Fix rare timing sync bugs causing modified items to duplicate or all items to disappear

### ISSUE THREAD

**Issue by androidseb** [androidseb/mapmarker#80]
## Duplicated items

Under specific circumstances, folders or POIs could get duplicated with the following chain of events:

* Use a cloud-synced map
* Edit an item (e.g. change a POI's color and save it)
* Start cloud sync (starts automatically with default settings)
* Before the cloud sync completes, edit the same item again (e.g. change the POI's color to yet another color and save it)
* Saving the edit must happen at the same time as the cloud index file is being uploaded by the current cloud sync
* The sync will get canceled by the edit and start again
* At the end of the second cloud sync, the edited item will be duplicated

**Note:** avoiding edits while the cloud sync is happening (disabling automatic cloud sync makes this easier) will prevent this issue from happening.

**Workaround:** delete the duplicated items manually.

## All items disappear

All map items can disappear after a cloud sync with the following chain of events:

* Use a cloud-synced map on two devices (Device A and Device B)
* Have device A and device B synced and up to date
* Make an edit from device A and sync it
* Immediately after, sync from device B

**Notes:**
* this bug only happens with the Google Drive API
* this bug is caused by a combination of two issues:
    * When querying a cloud map data file to the Google Drive API, a search query is made, and it can return "not found" for a freshly created file (up to 10 seconds from testing) - it probably takes some time for the Google Drive systems to index the file name to be searchable
    * When receiving a "not found" result from the Google Drive API, Map Marker assumes the "updated" cloud map is empty, which is why all items are removed - a correct implementation would be to throw an error when not finding the data map file referenced by the index file
* this bug has an element of randomness to it, it doesn't happen all the time, it depends on how long the Google Drive systems take to index the newly uploaded map data file to make it become available in the search API request, sometimes it's instant and the bug does not happen, sometimes it can take up to 10 seconds and the bug can happen
* this bug can also be encountered using a single device, by canceling the sync while the index file upload is happening, then triggering another sync quickly after that, but it's much trickier to reproduce

**Workaround:** use the cloud sync view history + restore feature to recover the previous data.

**Comment by fraiyah** [comment]
finally, i hope you can fix this  thank you been annoyed of this bug every time i iterrupt the app

**Comment by androidseb** [comment]
These bugs are now fixed as of version 3.10.0-beta-730.
