### ISSUE TITLE
Folder Names & Cloud Synch

### ISSUE THREAD

**Issue by Mike-T-17BSL** [androidseb/mapmarker#81]
I'm sorry i'm not a programmer so unsure how to add requests.

I'm working with map Marker between 2 computers and my iphone - I've created some surveys and captured the data and associated photos on my iphone. I can access the folders and photos on my iphone and computer 1. I renamed the folder on computer 1 to something meaningful, but the name doesn't seem to be available on computer 2 so I'm struggling to access the files from additional PC.

Everything is cloud synch'd top the same Google Account

I would love to be able to replace the background map with an imported PDF/PNG (floor plan) so i can mark up when I'm surveying a building which does not have any internet access/wifi. This also requires to work in off-line mode, if i turn my phone into plane mode, the app continues to try and synch (it just thinks there is no signal), and sometimes crashes/freezes and won't allow me to do anything, a few app restarts later and I'm good, but in this mode i cant add any names for the POI or detail, so i had to resort to add standard incremental POI name, and add photos and mark my drawing with the POI name. So kind of working backwards, and as cant load a building floor plan, all my POI are on top of each other.

Also it would be great to be able to move through the phots hen selecting a POI as you can on a phone, swipe right - it would be great  to be able to move through the photos within a selected POI by arrow click or arrow right /left on keyboard.

**Comment by androidseb** [comment]
Hello, thank you for your message.

Github issues are meant for bug reports or feature ideas, and I can see your message has a bit of a mix also including a request for support. For support on how to use the app (e.g. cloud sync), please use the in-app email option to contact me, and I'll assist you through there.

I'll respond to your other points below.

>  would love to be able to replace the background map with an imported PDF/PNG (floor plan) so i can mark up when I'm surveying a building which does not have any internet access/wifi

The custom image-imported map background is already tracked here: https://github.com/androidseb/mapmarker/issues/31

> if i turn my phone into plane mode, the app continues to try and synch (it just thinks there is no signal), and sometimes crashes/freezes and won't allow me to do anything, a few app restarts later and I'm good, but in this mode i cant add any names for the POI or detail, so i had to resort to add standard incremental POI name

This sounds like a bug, the app should remain responsive even in plane mode, do you think you could find a way to replicate this issue consistently? If you can, then you could create a new issue with reproduction steps just for that bug, so I can look into fixing it.

> Also it would be great to be able to move through the phots hen selecting a POI as you can on a phone, swipe right - it would be great to be able to move through the photos within a selected POI by arrow click or arrow right /left on keyboard.

That's a good point, the PC experience is a bit odd in that regard and swiping with the mouse isn't exactly intuitive for a PC user, I've added this to the backlog here:
https://github.com/androidseb/mapmarker/issues/86

With this, I believe all the points you mentioned are accounted for, so I'll close this issue now, feel free to re-open if you want to follow up, thanks.
